local_costmap:
  global_frame: odom          # continu, sans sauts de corrections SLAM
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5

  rolling_window: true
  width: 4.0
  height: 4.0
  # 3 cm : assez fin pour les pieds de chaises/câbles du labo, assez léger
  # pour tenir 5 Hz sur le PC
  resolution: 0.03

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
